### ISSUE TITLE
Case confusion in the output format API parameter.

### ISSUE THREAD

**Issue by lahvak** [drdrew42/renderer#27]
According to the documentation, specifically the README.md file, the name of the API parameter for specifying the output format is `outputFormat`, with uppercase F.  That does not seem to work, and when grepping the source for `outputFormat`, the line in README.md is the only one that comes up,  The all lowercase version, `outputformat`, seems to work, though.

**Comment by Miniland1333** [comment]
This is currently being worked on by Drew at d9776019fda47740980b21265cbb50bfbb084bfb

**Comment by drdrew42** [comment]
This fix will be merged in with the forthcoming update to PG-2.16
