### ISSUE TITLE
Support request for revised features in main WW project

### ISSUE THREAD

**Issue by taniwallach** [drdrew42/renderer#43]
The main project is making some changes to applet support, and this includes adding a new `ADD_JS_FILE()` method to PG, and support to handle the new change on the `webwork2` site.

Similar support will need to be added to this project.  The PG changes are likely to come in when a newer version of PG is included via the sub-module mechanism. However, the `webwork2` side changes need to be made in the renderer codebase.

  - https://github.com/openwebwork/pg/pull/489
  - https://github.com/openwebwork/webwork2/pull/1121

In particular see the changes to
  - `lib/WeBWorK/ContentGenerator/Problem.pm`
  - `lib/WeBWorK/ContentGenerator/GatewayQuiz.pm`

**Comment by drdrew42** [comment]
I've been working on a branch that incorporates `ADD_JS_FILE()` into the renderer process. I've seen the latest round of changes from @drgrice1, and I have yet to test out the new modifications - but I was successful in integrating the previous iteration.

The PG submodule will be updated when the new version is released, if not before. I will also be looking to shift the renderer's PG submodule to be based off of openwebwork/pg

**Comment by drgrice1** [comment]
Note the main project has also added the `ADD_CSS_FILE()` method to PG (added in https://github.com/openwebwork/pg/pull/428).  The renderer will need to be updated for that as well.

**Comment by drgrice1** [comment]
@drdrew42:  What do you mean by the previous iteration and the newest modifications?  Are you talking about the "Fix Applets in Gateway Quizzes" pull requests or more general changes to the code?  I don't think there have been any changes to those pull requests since you looked at them before.

**Comment by drdrew42** [comment]
I must have misunderstood - I thought I received notifications of an update. But now that I look back, the changes are dated back to December. My mistake, it must have been a request for review.

I do have updates ready for the renderer to incorporate the "fix applets in gateway quizzes" changes to pg/webwork2 (both for JS and CSS files).

**Comment by drgrice1** [comment]
Yeah, sorry.  I was prodding you for a review!

**Comment by drdrew42** [comment]
We are all up-to-date with 2.16 -- so I think that resolves this issue.

**Comment by taniwallach** [comment]
@drdrew42 - Thanks!

It seems that there is a need to explain in the docs how to properly update everything using Git without making a full new clone of the entire renderer repo. At least for me, a simple `git submodule update` did not suffice this time.

My problem seems to be that my local install was cloned a long time ago, and still had the source URL for PG as the rederly fork.  I think I managed to get it fixed, but am not sure that what I did is the best approach. I based the approach on things I read in https://stackoverflow.com/questions/913701/how-to-change-the-remote-repository-for-a-git-submodule  and got it updated essentially by removing the old submodule before reinstalling it:

```
git submodule deinit lib/PG
git submodule update --init lib/PG
```

Providing updated instructions mentioning the need for `git submodule update` in the `README.md` file as something to do is probably important, but I am not certain how many people need the more complex approach, as it apparently is only needed if the source Git URL for the submodule was out-dated.

**Comment by drdrew42** [comment]
Understood -- the submodule is now being pulled from a branch in my pg fork, actually. So it's changed hands several times. The current need for targeting a fork _other_ than openwebwork/pg is due to the speed boost that's provided by keeping a pre-populated pg translator on hand for each request. This approach is not supported in ww2, but reduces render times by roughly 30%...
