### ISSUE TITLE
Fix README.md - change to master repo

### ISSUE THREAD

**Issue by taniwallach** [drdrew42/renderer#44]
The line
```
git clone --recursive https://github.com/rederly/renderer container/
```
in `README.md` probably needs to be replaced by
```
git clone --recursive https://github.com/drdrew42/renderer container/
```

However, maybe the main repo should be transferred to openwebwork. I just made a standaloneRendered team there, but as team creator - I'm on it. https://github.com/orgs/openwebwork/teams/standalonerenderer/members

**Comment by dlglin** [comment]
I have cloned the renderer in openwebwork, and assigned the same permissions as the webwork2 and pg repositories.  Since @drdrew42 is part of the release managers team in openwebwork, he has commit access to the repo there.

**Comment by taniwallach** [comment]
> I have cloned the renderer in openwebwork, and assigned the same permissions as the webwork2 and pg repositories. Since @drdrew42 is part of the release managers team in openwebwork, he has commit access to the repo there.

I think it would be better to change the ownership of the main repository and not have openwebwork's copy be a fork of @drdrew42's repository. This is not urgent, but should be better for the long-term.

**Comment by taniwallach** [comment]
Fixed in https://github.com/drdrew42/renderer/commit/b4167db9f8308e9c0923fa43b7c67e29ae4b4c2a
