### ISSUE TITLE
Add format with "Submit" and "Preview"

### ISSUE THREAD

**Issue by taniwallach** [drdrew42/renderer#6]
I recommend adding a format with both the "Preview My Answers" and "Submit Answers" button but without the "Show correct answers" button.

**Comment by drdrew42** [comment]
`Classic` format gives 'preview' and 'submit' without the 'show correct answers' option.

**Comment by Miniland1333** [comment]
![image](https://user-images.githubusercontent.com/12994749/113663908-b3f26980-965f-11eb-8fe0-bdca0508bbb9.png)
This is what the `classic` format looks like and I believe it is what you are looking for.

I believe this issue can be closed.
